// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqMvVw5TWxQVHblxFtqbqK88KMwy5mcG8',
    appId: '1:1061990831640:web:968427eb54b26e8501556d',
    messagingSenderId: '1061990831640',
    projectId: 'medicq-498f1',
    authDomain: 'medicq-498f1.firebaseapp.com',
    storageBucket: 'medicq-498f1.firebasestorage.app',
    measurementId: 'G-5741HEFS1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgkd3wws-UFevhBnHGpvYmShnVR_uByUw',
    appId: '1:1061990831640:android:5ff8db9c96abc59b01556d',
    messagingSenderId: '1061990831640',
    projectId: 'medicq-498f1',
    storageBucket: 'medicq-498f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy3Qaw7H-LT03xos5HDH2beulASlaacO8',
    appId: '1:1061990831640:ios:4060a79c23fd813001556d',
    messagingSenderId: '1061990831640',
    projectId: 'medicq-498f1',
    storageBucket: 'medicq-498f1.firebasestorage.app',
    iosBundleId: 'com.example.medicQAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy3Qaw7H-LT03xos5HDH2beulASlaacO8',
    appId: '1:1061990831640:ios:4060a79c23fd813001556d',
    messagingSenderId: '1061990831640',
    projectId: 'medicq-498f1',
    storageBucket: 'medicq-498f1.firebasestorage.app',
    iosBundleId: 'com.example.medicQAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqMvVw5TWxQVHblxFtqbqK88KMwy5mcG8',
    appId: '1:1061990831640:web:97af574716bc944201556d',
    messagingSenderId: '1061990831640',
    projectId: 'medicq-498f1',
    authDomain: 'medicq-498f1.firebaseapp.com',
    storageBucket: 'medicq-498f1.firebasestorage.app',
    measurementId: 'G-DC3HFWJ7DM',
  );
}
